### ISSUE TITLE
Error after sending a msg in the bot

### ISSUE THREAD

**Issue by itsmo-ks** [hyperionhex/TelePaLM#1]
https://pastebin.com/fkCfa5SH

**Comment by hyperionhex** [comment]
> https://pastebin.com/fkCfa5SH

-Make sure your Google Cloud project that contains the API key has the Generative AI API enabled. It may not be enabled by default.
-Try removing any location parameters when calling the API. Some of them may not support geographic targeting.
-Double check the restrictions in the API documentation - there may be notes on location usage.
-Try using a different model with generate_text() rather than the default, as some models have more restrictions.
-If you are trying to use the API from a specific geographic region, it's possible that Google has not enabled the API there yet. You may need to use a VPN or proxy to call from a supported region.
-As a last resort, you can try reaching out to Google Cloud support for assistance on the FailedPrecondition error.
